# Provider padrão
LLM_PROVIDER = "sabia"

# Credenciais Sabiá
SABIA_API_KEY = "113507116394378398559_e28226e4557ecef7"
SABIA_BASE_URL = "https://chat.maritaca.ai/api/v1/chat/completions"

# OpenAI (se quiser alternar)
OPENAI_API_KEY = ""

# Modelos
MODEL_GPT = "gpt-4o-mini"
MODEL_SABIA = "sabia-3.1"

# RAG
CHUNK_SIZE = "1100"
CHUNK_OVERLAP = "200"
TOP_K = "6"
USE_BM25 = "true"

# Embedding
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
